name: Test bash actions in Github Actions

on:
    workflow_dispatch:
        inputs :
            appName:
              description: AppName
              required: true
              default: visibleapisandbox01
              type: choice
              options:
                - visibleapisandbox01
                - visibleapisandbox02
             
            slot:
              description: Deploy to slot
              required: true
              default: main
              type: choice
              options:
                - main
                - testing
                - stage

jobs:
    print-variable:
        runs-on: ubuntu-latest
        steps:
            # - name: Set Publish Profile
            #   id: setPublishProfile
            #   run: |
            #     if [[ "${{ github.event.inputs.appName }}" == "visibleapisandbox01" ]]  &&  [[ "${{ github.event.inputs.slot }}" == "main" ]]; then
            #     echo "::set-output name=publishProfile::${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_SANDBOX01 }}"
            #     elif [[ "${{ github.event.inputs.appName }}" == "visibleapisandbox01" ]]  &&  [[ "${{ github.event.inputs.slot }}" == "testing" ]]; then
            #     echo "::set-output name=publishProfile::${{ secrets.PUBLISH_PROFILE_TESTING }}"
            #     elif [[ "${{ github.event.inputs.appName }}" == "visibleapisandbox02" ]]  &&  [[ "${{ github.event.inputs.slot }}" == "stage" ]]; then
            #     echo "::set-output name=publishProfile::${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_SANDBOX02 }}"
            #     else
            #     echo "Conditions not met correctly. Please check the inputs and provide correct conditions."
            #     exit 1
            #     fi

            - name: Set Publish Profile Check point
              id: setPublishProfile
              run: |
                if [[ "${{ github.event.inputs.appName }}" == "visibleapisandbox01" ]]  &&  [[ "${{ github.event.inputs.slot }}" == "main" ]]; then
                echo "::set-output name=publishProfile::AZUREAPPSERVICE_PUBLISHPROFILE_SANDBOX01"
                elif [[ "${{ github.event.inputs.appName }}" == "visibleapisandbox01" ]]  &&  [[ "${{ github.event.inputs.slot }}" == "testing" ]]; then
                echo "::set-output name=publishProfile::PUBLISH_PROFILE_TESTING"
                elif [[ "${{ github.event.inputs.appName }}" == "visibleapisandbox02" ]]  &&  [[ "${{ github.event.inputs.slot }}" == "stage" ]]; then
                echo "::set-output name=publishProfile::AZUREAPPSERVICE_PUBLISHPROFILE_SANDBOX02"
                else
                echo "Conditions not met correctly. Please check the inputs and provide correct conditions."
                exit 1
                fi
            
            - name: Print Publish Profile
              run: echo "Publish Profile is ${{ steps.setPublishProfile.outputs.publishProfile }}"