name: Test bash actions in Github Actions

run-name: To print ${{github.event.inputs.Name}}

on:
    workflow_dispatch:
        inputs :
            Name:
              description: Name
              required: true
              default: ""
              type: string
             

jobs:
    print-variable:
        runs-on: ubuntu-latest
        steps:
            - name: Print the name
              run: echo "The name is ${{github.event.inputs.Name}}"