name: Test bash actions in Github Actions

run-name: To print ${{github.event.inputs.Name}}

on:
    workflow_dispatch:
        inputs :
            Name:
              description: Name
              required: true
              default: ""
              type: string
             

jobs:
    print-variable:
        runs-on: ubuntu-latest
        steps:
            - name: Print the name
              run: |
                echo "${{github.event.inputs.Name}}"
                echo "${{github.repository}}"

            - name: Checkout repository
              uses: actions/checkout@v3
              with: 
                clean: false
                fetch-depth: 0

            - name: Get the changed files
              run: |
                changed_files=$(git log --name-only --pretty=format: --since="24 hours ago" main)
                filtered_files=$(echo "$changed_files" | { grep '\.yml' || true; })
                echo "$filtered_files"
                count=$(echo ${#filtered_files})
                echo "$count"
                if [ $count -eq 0 ];
                then 
                echo "exiting as no hostname since last 24 hours"
                exit 0;
                fi
                changed_files=$filtered_files
                count=$(echo ${#changed_files})
                mapfile -t array <<< "$changed_files"
                echo "$array"