name: "Workflow to pass properties to a subworkflow"

on:
    workflow_dispatch:
        inputs:
            file:
                description: "File to process"
                required: true
                type: string
                default: "file.txt"

jobs:
    print-files:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Print file
              run: echo "The files are ${{ github.event.inputs.file }}"
